### ISSUE TITLE
Importing Backup Fails with missing VPReg.stg

### ISSUE THREAD

**Issue by gonzonia** [mmattner/vPinBackupManagerApp#7]
I'm trying to use backups from one machine to restore on a new machine. When I attempt to import some of the backups I get this error in the log:

`2024-11-07 11:34:00.303 [INFO] MainWindow.buttonImportBackups_Click: User requested import of 1 game backups
2024-11-07 11:34:00.321 [INFO] MainWindow.importBackupsOperation: Importing 1 valid game backups (from 1 requested) with total uncompressed size=757.752 MB
2024-11-07 11:34:00.321 [INFO] MainWindow.importBackupsOperation: Importing game "Visual Pinball X/Leprechaun King" with expected size=757.752 MB
2024-11-07 11:34:08.903 [INFO] BackupManager.PerformRestoreLogging: Importing file "C:\vPinball\visualpinball\Tables\Leprechaun King.vpx"
2024-11-07 11:34:12.568 [EROR] MainWindow.importBackupsOperation: An exception occured importing C:\vPinball\backups\Visual Pinball X\Leprechaun King.vpinzip. Processing cancelled.
System.IO.FileNotFoundException: Could not find file 'C:\vPinball\visualpinball\User\VPReg.stg'.
File name: 'C:\vPinball\visualpinball\User\VPReg.stg'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at OpenMcdf.CompoundFile.LoadFile(String fileName)
   at OpenMcdf.CompoundFile..ctor(String fileName, CFSUpdateMode updateMode, CFSConfiguration configParameters)
   at vPinBackupManager.VPRegUtilities.RestoreEntry(String filePath, String backupFilePath, String entryName) in ./Utilities/VPRegUtilities.cs:line 185
   at vPinBackupManager.BackupManager.restoreFile(String emulator, Int64 gameId, String gameName, String gameFileName, String tempBackupFolderPath, String backupPath, String filterStr, GameVariableDetails gameVariableDetails, FILE_SOURCE fileSource, FILTER_PATH_TYPE filterType, Dictionary`2 filterDirs, IProgress`1 progressFunc, Int64 gameSize, Int64 processedSize, Decimal startingPercent, String operationMulti, Boolean provideLogMessages) in ./Managers/BackupManager.cs:line 3582
   at vPinBackupManager.BackupManager.restoreFiles(String tempBackupFolderPath, String emulator, Int64 gameId, String gameName, String gameFileName, GameVariableDetails gameVariableDetails, Int64 gameSize, IProgress`1 progressFunc, Decimal startingPercent, String operationMulti, List`1 otherGamesUsingFiles) in ./Managers/BackupManager.cs:line 3842
   at vPinBackupManager.BackupManager.restoreGame(String emulator, Int64 gameId, String gameName, String gameFileName, GameVariableDetails gameVariableDetails, Int64 gameSize, IProgress`1 progressFunc, Decimal startingPercent, String operation, String operationMulti, List`1 otherGamesUsingFiles) in ./Managers/BackupManager.cs:line 3907
   at vPinBackupManager.BackupManager.importGame(String sourceBackupFilePath, Int64 gameSize, IProgress`1 progressFunc, List`1 otherGamesUsingFiles) in ./Managers/BackupManager.cs:line 4185
   at vPinBackupManager.MainWindow.importBackupsOperation(Object sender, DoWorkEventArgs e) in ./MainWindow.xaml.cs:line 3560
`

**Comment by mmattner** [comment]
Hi,
Thanks for the ticket, I will start looking at this, this week. Sorry for the delayu, have been rounding out my work task prior to Christmas.

It appears fundamentally the issue is an entry needs to be added to the VPReg.stg file which is empty. The solution will be in this case to add a default empty VPReg.stg file to use as a basis if one doesn't exist.

**Comment by gonzonia** [comment]
Thanks. I do think that would be the solution. I ended up copying my VPReg.stg from my old machine to the new one to make it work.

**Comment by gonzonia** [comment]
No worries on the delay. I appreciate everything the developers all over this hobby do.  I'm just happy to be able to contribute in a small way like this to make things better.

**Comment by mmattner** [comment]
Sorry for the delay. I should be back on this now, Ive had to replace my development laptop, the new one has now arrived.

**Comment by mmattner** [comment]
Hi @gonzonia just closing out this ticket and confirming you are happy that this is now working (delivered along with ticket #10 related to files getting deleted).
